# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bloader < Formula
  desc ""
  homepage ""
  version "0.1.11"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ablankz/bloader/releases/download/v0.1.11/bloader_ 0.1.11_Darwin_x86_64.tar.gz"
      sha256 "17900ffd0eda21cc0d12fe5b13fc45df5b0171719b2fa7a3352ee810b46e08f5"

      def install
        bin.install "bloader"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ablankz/bloader/releases/download/v0.1.11/bloader_ 0.1.11_Darwin_arm64.tar.gz"
      sha256 "10c7b608aa7bf167935d953dbc75f0f3960a29ffc2f1a1accb96c82d4ef68fa8"

      def install
        bin.install "bloader"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ablankz/bloader/releases/download/v0.1.11/bloader_ 0.1.11_Linux_x86_64.tar.gz"
        sha256 "dbe5452994b807a94e3ad8f5d3e956ccab079289afdaf670a271619b40ab16df"

        def install
          bin.install "bloader"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ablankz/bloader/releases/download/v0.1.11/bloader_ 0.1.11_Linux_arm64.tar.gz"
        sha256 "080b3521e27c9a41623a3369be144d9ce8bdb0226a4ac31f97f8d8ede3de1db0"

        def install
          bin.install "bloader"
        end
      end
    end
  end
end
