# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bloader < Formula
  desc ""
  homepage ""
  version "0.1.12"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ablankz/bloader/releases/download/v0.1.12/bloader_ 0.1.12_Darwin_x86_64.tar.gz"
      sha256 "50f874fa004bc53d155882b7e6fb77e72ce9ebcc1b00811a86c4ed09df4d9d8b"

      def install
        bin.install "bloader"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ablankz/bloader/releases/download/v0.1.12/bloader_ 0.1.12_Darwin_arm64.tar.gz"
      sha256 "21daaf57b97acba55deceb48a023a747a8a53618b32351db003c50be4fbe7cdf"

      def install
        bin.install "bloader"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ablankz/bloader/releases/download/v0.1.12/bloader_ 0.1.12_Linux_x86_64.tar.gz"
        sha256 "85dbf59b927814ab22fa530b74475228de6aa1b8fba717e4a6f79213c540a570"

        def install
          bin.install "bloader"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ablankz/bloader/releases/download/v0.1.12/bloader_ 0.1.12_Linux_arm64.tar.gz"
        sha256 "7d98e2c435f9193649713bd1650e910449c56d373869d54683632bb459eccf2d"

        def install
          bin.install "bloader"
        end
      end
    end
  end
end
